[package]
name = "cerulean-web"
description = "CErulean のブラウザ版（wasm）のエントリ"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cerulean-core.workspace = true
cerulean-fat.workspace = true
cerulean-net.workspace = true
wasm-bindgen.workspace = true
